Create README.md
BIM7AA/BIM7AA_Properties_DataPack pull request #4
Opened 2022-04-22 07:54 UTC by DuncanLithgow

2022-04-22 18:17 UTC, tsolsen requested changes
Se kommentarer.

2022-04-22 18:17 UTC, tsolsen commented on README.md
> +   * FVK ( [Forvaltningklassifaktion](https://www.lbf.dk/om-lbf/lbf-orienterer/2009/8/forvaltnings-klassifikation/)
reference er [Forvaltningsklassifikation](https://www.lbf.dk/publikationer/2014-forvaltnings-klassifikation/)

2022-04-22 18:17 UTC, tsolsen commented on README.md
> +   * BC SfB ( [Samarbetskommitten for Byggnadsfragor)](https://www.designingbuildings.co.uk/wiki/CI/SfB)
reference er [BC/SfB-bygningsdelstavle](https://molio.dk/boeger/sfb-1988-bygningsdeltavle/c-23/p-2193)

2022-04-23 10:50 UTC, merged

2022-04-23 18:28 UTC, DuncanLithgow commented
Sorry for pushing so many separate commits, I thought I was only saving to my master. I have a lot to learn about git and github.